name: test_lab
version: '1.0'
summary: Test Lab
description: Testing ios integration testing

confinement: strict
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

parts:
  super-cool-app:
    plugin: flutter
    source: https://github.com/icarusdust/test_lab.git
    flutter-target: lib/main.dart

apps:
  super-cool-app:
    command: test_lab
    extensions: [flutter-dev]
