
name: test-lab
version: git
summary: Super Cool App
description: Super Cool App that does everything!
confinement: strict
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  super-cool-app:
    command: super_cool_app
    extensions: [flutter-master]

parts:
  super-cool-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
